# Generated by Django 5.2.5 on 2025-08-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='Yksikko',
        ),
        migrations.RenameField(
            model_name='aines',
            old_name='quant',
            new_name='maara',
        ),
        migrations.CreateModel(
            name='Vaihe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuvaus', models.TextField()),
                ('aika_minuuttia', models.IntegerField(default=0)),
                ('jarjestys', models.IntegerField()),
                ('resepti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaiheet', to='app.resepti')),
            ],
            options={
                'ordering': ['jarjestys'],
            },
        ),
    ]
