# Generated by Django 5.2.5 on 2025-08-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_unit_yksikko_rename_quant_aines_maara_vaihe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aines',
            old_name='unit',
            new_name='yksikko',
        ),
    ]
