# Generated by Django 5.2.5 on 2025-08-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_unit_aines_yksikko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aines',
            name='maara',
        ),
        migrations.RemoveField(
            model_name='aines',
            name='yksikko',
        ),
        migrations.CreateModel(
            name='ReseptiAines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maara', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resepti_aines', to='app.aines')),
                ('yksikko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.yksikko')),
            ],
        ),
        migrations.AlterField(
            model_name='resepti',
            name='ainekset',
            field=models.ManyToManyField(related_name='reseptit', to='app.reseptiaines'),
        ),
    ]
