# Generated by Django 5.2.5 on 2025-08-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_aines_maara_remove_aines_yksikko_reseptiaines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseptiaines',
            name='aines',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reseptiaines',
            name='yksikko',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Aines',
        ),
        migrations.DeleteModel(
            name='Yksikko',
        ),
    ]
