# Generated by Django 5.2.5 on 2025-08-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_reseptiaines_aines_alter_reseptiaines_yksikko_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaihe',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='vaihe',
            name='jarjestys',
        ),
        migrations.RemoveField(
            model_name='vaihe',
            name='resepti',
        ),
        migrations.AddField(
            model_name='resepti',
            name='vaiheet',
            field=models.ManyToManyField(related_name='reseptit', to='app.vaihe'),
        ),
    ]
